name: onlineshopping
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.1
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  provider: ^6.1.2
  mix: ^1.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
