// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_vIdxMabNPRrdS_KQQhXuCrTCy-znANA',
    appId: '1:107446514128:web:8690dc6f7e01c2b5c9c9d5',
    messagingSenderId: '107446514128',
    projectId: 'shoppee-8c502',
    authDomain: 'shoppee-8c502.firebaseapp.com',
    storageBucket: 'shoppee-8c502.appspot.com',
    measurementId: 'G-RZSP122J57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-amZwX2UPFLTjBCrG0-NjTSo4fu3zs9I',
    appId: '1:107446514128:android:3ac942d7f0a1414ac9c9d5',
    messagingSenderId: '107446514128',
    projectId: 'shoppee-8c502',
    storageBucket: 'shoppee-8c502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzJVpsrNcsTUh8PWmX3x2-S_ZnDpft-Os',
    appId: '1:107446514128:ios:a202dfa32562b4a2c9c9d5',
    messagingSenderId: '107446514128',
    projectId: 'shoppee-8c502',
    storageBucket: 'shoppee-8c502.appspot.com',
    iosClientId: '107446514128-u5avk81gv7ml9ulce5k39dg66gdd5f6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineshopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzJVpsrNcsTUh8PWmX3x2-S_ZnDpft-Os',
    appId: '1:107446514128:ios:a202dfa32562b4a2c9c9d5',
    messagingSenderId: '107446514128',
    projectId: 'shoppee-8c502',
    storageBucket: 'shoppee-8c502.appspot.com',
    iosClientId: '107446514128-u5avk81gv7ml9ulce5k39dg66gdd5f6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineshopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_vIdxMabNPRrdS_KQQhXuCrTCy-znANA',
    appId: '1:107446514128:web:034710f9692e5bc6c9c9d5',
    messagingSenderId: '107446514128',
    projectId: 'shoppee-8c502',
    authDomain: 'shoppee-8c502.firebaseapp.com',
    storageBucket: 'shoppee-8c502.appspot.com',
    measurementId: 'G-14K30890L3',
  );

}